### ISSUE TITLE
Attempted to call an undefined method named "getCacheDriver"

### ISSUE THREAD

**Issue by geoffroyp** [doctrine-extensions/DoctrineExtensions#2448] opened 2022-04-29 15:57 UTC
There is currently an incompatibility with version v3.6.0, when used with  `doctrine/persistence` v3.0.0. 
Once updated, we get the following error message:

`Attempted to call an undefined method named "getCacheDriver" of class "Doctrine\Bundle\DoctrineBundle\Mapping\ClassMetadataFactory".`

More details (call stack, possible faulty line, and such) has already been discussion in the issues board of `doctrine/doctrine-bundle` and can be found here: https://github.com/doctrine/DoctrineBundle/issues/1514

**Comment by KaiGrassnick** [comment] 2022-04-29 21:53
Temporary Workaround (at least for me)

1. `composer require doctrine/persistence ^2.2`
2. `composer require gedmo/doctrine-extensions ^3.6`

**Comment by frizquierdo** [comment] 2022-04-30 05:39
> Temporary Workaround (at least for me)
> 
>     1. `composer require doctrine/persistence ^2.2`
> 
>     2. `composer require gedmo/doctrine-extensions ^3.6`

I have those versions, and the conflict occurred when upgrading to sf 5.4.8 from 5.47

**Comment by gnito-org** [comment] 2022-04-30 10:55
The problem is caused by [V3.6.0](https://github.com/doctrine-extensions/DoctrineExtensions/blob/20e682c5c376faa4c88421453707741e1dd1f131/composer.json#L48) requiring `"doctrine/persistence": "^2.2"` and V3.1.0 not requiring `doctrine/persistence` at all. If you have `"doctrine/persistence": "^3.0"`, `gedmo/doctrine-extensions` is downgraded to V3.1.0. That version makes a call to a Doctrine method that does not exist in Doctrine V3.

**Comment by franmomu** [comment] 2022-04-30 11:19
Until we support `doctrine/persistence` 3, the solution here is to stick to the latest version of this package (3.6.0) and do not downgrade to 3.1.0. This can be done by requiring `"gedmo/doctrine-extensions": "^3.6"` and composer won't let upgrade `doctrine/persistence` to version 3.

**Comment by tacman** [comment] 2022-05-05 16:05
Since Symfony 6.1 is in beta now and will be released in a few weeks, I suspect this error will be pretty common (a simple "composer update").  Anytime timeline on this fix?

**Comment by patrickbussmann** [comment] 2022-05-08 15:48
Haha @tacman you're right - I also got this.
Thanks to Unit Testing 😉

And thanks @franmomu for short fix. 🥳

**Comment by franmomu** [comment] 2022-05-08 20:31
Closing this since this is not an issue using the latest version, to allow `doctrine/persistence` 3, https://github.com/doctrine-extensions/DoctrineExtensions/pull/2454 has been created.

**Closed by franmomu** 2022-05-08 20:31 UTC
