### ISSUE TITLE
Composer require dev conflicts

### ISSUE THREAD

**Issue by jdempster** [doctrine-extensions/DoctrineExtensions#1737] opened 2017-01-09 11:25 UTC
`doctrine/common` is confusingly required both in `require` and `require-dev`.

```
$ composer diagnose
Checking composer.json: WARNING
doctrine/common is required both in require and require-dev, this can lead to unexpected behavior
```

`doctrine/orm` is marked as only a dev requirement of the library. If `doctrine/orm` is moved into `require` then `doctrine/common` is included as part of `doctrine/orm`.

**Comment by stof** [comment] 2017-01-09 11:41
the ORM cannot be moved as a normal requirement, as it would break things for ODM users

**Comment by stof** [comment] 2017-01-09 11:42
the issue is just that doctrine/common is indeed duplicated in require-dev, which does not make sense

**Comment by phansys** [comment] 2021-11-06 01:47
This issue is not present in the [current stable version](https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.2.0).
Closing.

**Closed by phansys** 2021-11-06 01:47 UTC
Labels: Bug
