### ISSUE TITLE
[Mapping] Metadata for inherited mapped classes are not well collected

### ISSUE THREAD

**Issue by gaelreyrol** [doctrine-extensions/DoctrineExtensions#2600] opened 2023-03-10 11:41 UTC
## Subject

The `ExtensionMetadataFactory` is not collecting as expected configuration from metadata in particular conditions.

Here are the conditions I managed to define to get this unexpected behavior:

- Entity using ORM Inherited entity / Mapped super class with any extensions.
- Cache change between entity manipulations.

This [issue](https://github.com/doctrine-extensions/DoctrineExtensions/issues/2463) is similar but has been closed considering that specifying the metadata cache pool solves the problem, which is true but does not solves the root cause of the problem.

@dpfaffenbauer pointed out this [issue](https://github.com/doctrine/orm/issues/8866) from `doctrine/orm` reporting that not all classes metadata are loaded in production and derives on the `ClassMetadataFactory` interface method `hasMetadataFor` usage. The method name is misleading its usage as the interface comments states:

> Checks whether the factory has the metadata for a class loaded already.

This method does not return false if the entity has no metadata, it returns false if the cache does not contain any metadata for the given class which in our case can occur for mapped super classes / inherited entities. 

Therefor the method `isTransient` from the same interface can be used in combination to check if mapped super class metadata should be loaded and cached which is exactly what is missing in the `ExtensionMetadataFactory` to fully collect metadata for mapped super classes.

## Minimal repository with the bug

https://github.com/gaelreyrol/DoctrineExtensions/tree/fix-inherited-classes-metadata-collection

## Steps to reproduce

Run the test `MappingEventSubscriberTest::testGetMetadataFactoryCacheFromDoctrineForSuperClassExtension()`.

https://github.com/gaelreyrol/DoctrineExtensions/blob/fix-inherited-classes-metadata-collection/tests/Gedmo/Mapping/MappingEventSubscriberTest.php#L71

## Expected results

With this [fix](https://github.com/gaelreyrol/DoctrineExtensions/compare/main...gaelreyrol:DoctrineExtensions:fix-inherited-classes-metadata-collection#diff-743309499de09a3a2dccf90b49db367b9ec8a0602fb2567167b156826d3f8107R117) applied in `ExtensionMetadataFactory::getExtensionMetadata()` the test should pass.

If this explanation is self sufficient, I can submit a PR with the branch I created containing the fix and the related test.

Regards

**Comment by phansys** [comment] 2023-03-11 02:23
Hi @gaelreyrol.

Is the metadata cache configuration intended to be updated at runtime? Is this behavior documented? I'd like to understand if the proposed fix is in the right direction or if we should disallow this kind of change at all.

Thanks!

**Comment by gaelreyrol** [comment] 2023-03-11 15:14
Hi @phansys,

If you follow the implementation for this call [$this->objectManager->getClassMetadata($parentClass)](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Mapping/ExtensionMetadataFactory.php#L119) implemented by `doctrine/persistence` package, it leads to the abstract class `AbstractClassMetadataFactory` and its method [getMetdataFor](https://github.com/doctrine/persistence/blob/3.0.x/src/Persistence/Mapping/AbstractClassMetadataFactory.php#L175) which returns the class metadata if cached and if not loads it directly from the file. So I guess if it should not be updated at runtime, doctrine maintainers would not have implemented it that way.

What do you thing?

**Comment by phansys** [comment] 2023-03-17 20:02
IIUC, what you are trying to fix is the missing metadata returned by `ExtensionMetadataFactory::getExtensionMetadata()`, when there is no existing cache.
If it is the case, I think the test should organized this way:
* A test covering the behavior without cache;
* A test covering the behavior with cache.

What is confusing to me, is that in your current [fix](https://github.com/gaelreyrol/DoctrineExtensions/compare/main...gaelreyrol:DoctrineExtensions:fix-inherited-classes-metadata-collection#diff-743309499de09a3a2dccf90b49db367b9ec8a0602fb2567167b156826d3f8107R117) you seem to be changing the cache driver instead of performing the comparison with and without cache. Please, correct me if I am wrong in my interpretation.

**Comment by X-Coder264** [comment] 2023-07-07 18:36
I've opened an issue on StofDoctrineExtensionsBundle package (https://github.com/stof/StofDoctrineExtensionsBundle/issues/455), turns out the root cause is actually this bug. I've tested the fix that the OP provided and it's working.

@gaelreyrol Could you please open a PR with that fix? If you don't have time for it I can do it instead. Thanks.

**Comment by yakobe** [comment] 2023-07-10 11:22
I seem to be having this issue too. @gaelreyrol could you PR that fix if it's suitable? Or are there still problems?

**Comment by yakobe** [comment] 2023-07-10 11:49
@phansys I have tested the proposed [fix](https://github.com/gaelreyrol/DoctrineExtensions/compare/main...gaelreyrol:DoctrineExtensions:fix-inherited-classes-metadata-collection#diff-743309499de09a3a2dccf90b49db367b9ec8a0602fb2567167b156826d3f8107R117) locally and it solves the problems with missing metadata for classes with `#[ORM\MappedSuperclass]`. Without the change the metadata is empty 😿

**Comment by joanna-bak-sourceability** [comment] 2023-07-20 09:18
We also have an issue with this. @franmomu is there any status update on this?

**Comment by franmomu** [comment] 2023-07-23 18:44
hey, sorry for taking so long, please send a PR, the fix looks fine, is the `$cmf->hasMetadataFor($parentClass)` part necessary?

**Comment by X-Coder264** [comment] 2023-07-23 23:31
@franmomu The PR has already been opened -> https://github.com/doctrine-extensions/DoctrineExtensions/pull/2651

**Closed** 2023-08-19 07:25 UTC
Labels: Bug
