### ISSUE TITLE
Root cannot be changed manually, change parent instead

### ISSUE THREAD

**Issue by GSadee** [doctrine-extensions/DoctrineExtensions#2254] opened 2021-10-04 11:32 UTC
Hello!

I'm not sure if the problem is in your repository or in https://github.com/doctrine/orm, but after the new tag of `doctrine/orm` has been released, I've got the following error:
```
Gedmo\Exception\UnexpectedValueException: Root cannot be changed manually, change parent instead in 
vendor/gedmo/doctrine-extensions/src/Tree/Strategy/ORM/Nested.php:145
``` 
on https://github.com/Sylius/Sylius repository during creation of a category with children ([the failing build](https://github.com/Sylius/Sylius/runs/3787124403?check_suite_focus=true#step:21:328)).

But if I checked correctly, the root is not set anywhere in Sylius, we only operate on setting the parent of our categories (taxons).

**Comment by AkenRoberts** [comment] 2021-10-05 01:42
Closing as a duplicate of #2155, please watch and/or contribute there for easier tracking. 🙇🏼

**Closed by AkenRoberts** 2021-10-05 01:42 UTC
