### ISSUE TITLE
Translatable broken on orm 2.10

### ISSUE THREAD

**Issue by signor-pedro** [doctrine-extensions/DoctrineExtensions#2256] opened 2021-10-05 05:22 UTC
Hello, this morning we had to downgrade to orm 2.9 and restore our production database from backup 😢 

This worked perfectly fine on `doctrine/orm` 2.9.*
```
$this->entityManager->persist(
    $entity = new Entity('in english'),
);

$this->entityManager->flush();

$entity->setTranslatableLocale('fr');
$this->entityManager->refresh($entity);

$entity->setName('in french');
$this->entityManager->persist($entity);
$this->entityManager->flush();
```
The result was as you'd expect - one record in the entity table for the _default_ locale, and one in the translation table.
```
$entityRepository->find(1)?->getName();
// => 'in english'
```

**Since orm 2.10.**, the record in the default language is overwritten with the latest translated string:
```
$entityRepository->find(1)?->getName();
// => 'in french'
```
Once again, this is actually overwritten on the database level. The string in the original language is lost. (The record on the translation table just duplicates the one on the entity table.)

Can anyone confirm/investigate please?

Thank you 🙏

**Comment by signor-pedro** [comment] 2021-10-05 06:03
I created a reproducible
https://github.com/signor-pedro/reproducible

**Comment by signor-pedro** [comment] 2021-10-05 06:40
I just noticed that in the `main` branch, there is already
```
"conflict": {
  "doctrine/orm": ">=2.10",
},
```
Just please tag this release ASAP so that other people don't destroy their prod databases 😄 🙏 
Thank you

**Comment by jorrit** [comment] 2021-10-05 15:17
I have this situation as well. When I update some entity, a related entity (several layers away) is updated where the default field is overwritten with the translation in the current language.

**Comment by AkenRoberts** [comment] 2021-10-05 15:29
[v3.2.0](https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.2.0) is tagged with the Composer conflict to hopefully prevent further issues for the time being.

**Comment by franmomu** [comment] 2021-11-06 20:18
Hi, thanks for reporting, could you try if https://github.com/doctrine-extensions/DoctrineExtensions/pull/2272 solves the issue? thanks!

**Comment by phansys** [comment] 2021-11-16 08:30
Thank you for reporting the issue @signor-pedro.
Now [3.3.0](https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.3.0) is released. Could you please confirm if the problem is fixed?

**Comment by larzuk91** [comment] 2021-12-20 20:44
I got hit by this problem and I can confirm that upgrading to latest version did fix the problem

**Comment by franmomu** [comment] 2021-12-21 09:37
Thanks! closing this one as it seems to be fixed, otherwise feel free to reopen

**Closed by franmomu** 2021-12-21 09:37 UTC
Labels: Bug, Translatable, Pending Author
